HAI
WAZZUP
I HAS A x ITZ 3
I HAS A y ITZ 2
I HAS A z ITZ FAIL
BUHBYE
SUM OF 5 AN 7 BTW MEOWMEOW MEOW
ALL OF x AN y AN z MKAY
BOTH SAEM x AN BIGGR OF x AN y
VISIBLE "HELLO WORLD" + "MEOW MEOW"
KTHXBYE
